# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 34a0f28999d853fd54074f872015ffbc1f62ceb0468e6fc3a504fa3567c711f0db27420d63b9347fdb3bdcc0755a7dcb55807505205c9f1f8ad153873adb4798

test:
  secret_key_base: 290ebb4b3b8c0d809efec7cf35c709545d4a99075ee2ce0836833826e1cf3d7699cd2eab6145419120d70385c048383defbc4dfc3f883082fa745032a588d67a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
