# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9b99a48e7eb597874b7f5929e228a7c8537736f66a316bfd4ce14c8ff9fdf8b962e2ef57a55d934af30908ccf602faeab57231e51c426844ec81281ab618d81

test:
  secret_key_base: 8abcf92b86aa19e728f17af9f2d46f5eb585ab44bf4e0b6f220bae091c92d2c9785bc8c0108e9e4b585c4d60f21a1c71df53944f5ebee6d30c13633515f50f41

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
